global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - 'host.docker.internal:8080'  # Gateway
        - 'host.docker.internal:8081'  # Transaction Service
        - 'host.docker.internal:8082'  # Banking Service
        - 'host.docker.internal:8083'  # Fraud Service
        - 'host.docker.internal:8084'  # Exchange Service
        - 'host.docker.internal:8085'  # Audit Service
