# config-server/src/main/resources/configurations/discovery-service.yml
# Eureka Discovery Service Configuration

server:
  port: ${DISCOVERY_SERVER_PORT:8761}

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: false
  client:
    # Discovery service doesn't register with itself
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # Disable self-preservation for demo (enable in production)
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    response-cache-update-interval-ms: 5000
    # Peer node configuration for HA (if needed)
    peer-node-read-timeout-ms: 1000

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

# Logging
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO